version: '3'
services:
  gpt-interface:
    image: gpt-interface-api
    build: ./gpt-interface-api
    ports:
      - "8000:8000"
    volumes:
      - ./gpt-interface-api:/app
    environment:
      - LOG_LEVEL=DEBUG
      - PYTHONUNBUFFERED=1
  # next-frontend: # This container is not for development, but for production
  #   container_name: react-frontend
  #   build: ./react-app
  #   ports:
  #     - "3000:3000"
  auth-api:
    image: auth-api
    build: ./auth-api
    volumes:
      - ./auth-api:/app
    ports:
      - "8001:8000"
  auth-db:
    image: mongo:latest
    container_name: auth-db
    ports:
      - "27017:27017"
    volumes:
      - /var/lib/mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
  image-proxy:
    # This was made entirely by gpt
    image: image-proxy-by-gpt
    build: ./image-proxy-by-gpt
    ports:
      - "3001:3001"
