version: '3'
services:
  gpt-interface:
    image: gpt-interface-api
    build: ./gpt-interface-api
    ports:
      - "8000:8000"
    volumes:
      - ./gpt-interface-api:/app
    environment:
      - LOG_LEVEL=DEBUG
      - PYTHONUNBUFFERED=1
  # next-frontend: # This container is not for development, but for production
  #   container_name: react-frontend
  #   build: ./react-app
  #   ports:
  #     - "3000:3000"
  image-proxy:
    # This was made entirely by gpt
    image: image-proxy-by-gpt
    build: ./image-proxy-by-gpt
    ports:
      - "3001:3001"
